const CONSTANTS = {
  /** LOGIN CONSTANTS */
  CREATE_USER: 'CREATE_USER',
  GET_USERS: 'GET_USERS',
  GET_USER: 'GET_USER',
  UPDATE_USER: 'UPDATE_USER',
  STORE_USERS: 'STORE_USERS',
  DELETE_USER: 'DELETE_USER',
  EDIT_USER: 'EDIT_USER',
  USER_SIGN_IN: 'USER_SIGN_IN',
  DELETE_USER_STORE: 'DELETE_USER_STORE',
  STORE_USER_FORM: 'STORE_USER_FORM',
  CLEAN_USER_FORM: 'CLEAN_USER_FORM',

  USER_STORE_FORM: 'USER_STORE_FORM',
  CLEAN_USER_STORE_FORM: 'CLEAN_USER_STORE_FORM',

  CREATE_ADMIN: 'CREATE_ADMIN',
  GET_ADMIN: 'GET_ADMIN',
  GET_ADMINS: 'GET_ADMINS',
  EDIT_ADMIN: 'EDIT_ADMIN',
  ADMIN_SIGN_IN: 'ADMIN_SIGN_IN',
  STORE_ADMINS: 'STORE_ADMINS',
  DELETE_ADMIN: 'DELETE_ADMIN',

  DELETE_ADMIN_STORE: 'DELETE_ADMIN_STORE',
  ADMIN_STORE_FORM: 'ADMIN_STORE_FORM',
  CLEAN_ADMIN_STORE_FORM: 'CLEAN_ADMIN_STORE_FORM',

  STORE_CURRENT_ADMIN: 'STORE_CURRENT_ADMIN',
  IS_AUTH: 'IS_AUTH',
  LOG_OUT: 'LOG_OUT',

  /** */
  ABRIR_MENU: 'ABRIR_MENU',
  CERRAR_MENU: 'CERRAR_MENU',
};

export default CONSTANTS;
